var INTERCEPTOR_CONFIG = {
  BRAINROT_PATTERNS: [
    { regex: /skibidi/i, category: "brainrot", severity: "high" },
    { regex: /fanum\s*tax/i, category: "brainrot", severity: "high" },
    { regex: /\brizz\b/i, category: "brainrot", severity: "high" },
    { regex: /gyatt/i, category: "brainrot", severity: "high" },
    { regex: /\bohio\b/i, category: "brainrot", severity: "medium" },
    { regex: /sigma\s*(grindset|male|edit)?/i, category: "brainrot", severity: "high" },
    { regex: /\bnpc\b/i, category: "brainrot", severity: "medium" },
    { regex: /mewing/i, category: "brainrot", severity: "medium" },
    { regex: /looksmaxx/i, category: "brainrot", severity: "medium" },
    { regex: /beta\s*bust/i, category: "brainrot", severity: "medium" },
    { regex: /grimace\s*shake/i, category: "brainrot", severity: "medium" },
    { regex: /baby\s*gronk/i, category: "brainrot", severity: "medium" },
    { regex: /sussy\s*baka/i, category: "brainrot", severity: "low" },
    { regex: /bombardilo/i, category: "brainrot", severity: "low" },
    { regex: /tralalero\s*tralala/i, category: "brainrot", severity: "low" },
    { regex: /tung\s*tung\s*tung\s*sahur/i, category: "brainrot", severity: "low" },
    { regex: /chimpanzini\s*bananini/i, category: "brainrot", severity: "low" },
    { regex: /boneca\s*ambalabu/i, category: "brainrot", severity: "low" },
    { regex: /among\s*us/i, category: "brainrot", severity: "low" },
  ],
  SOCIAL_ENGINEERING_PATTERNS: [
    { regex: /blind\s*date/i, category: "social_engineering", severity: "high" },
    { regex: /dating\s*challenge/i, category: "social_engineering", severity: "high" },
    { regex: /find\s*(me|my)\s*(a|an)\s*(girlfriend|boyfriend|partner)/i, category: "social_engineering", severity: "high" },
    { regex: /speed\s*dating/i, category: "social_engineering", severity: "high" },
    { regex: /pick\s*up\s*(line|artist|game)/i, category: "social_engineering", severity: "high" },
    { regex: /crush\s*confess/i, category: "social_engineering", severity: "high" },
    { regex: /would\s*you\s*rather\s*(date|kiss)/i, category: "social_engineering", severity: "high" },
    { regex: /rating\s*(girls|boys|people|kids)/i, category: "social_engineering", severity: "high" },
    { regex: /hotness\s*check/i, category: "social_engineering", severity: "high" },
    { regex: /sliding\s*into\s*dm/i, category: "social_engineering", severity: "medium" },
  ],
  RISKY_STUNT_PATTERNS: [
    { regex: /dare\s*challenge/i, category: "risky_stunts", severity: "high" },
    { regex: /extreme\s*challenge/i, category: "risky_stunts", severity: "high" },
    { regex: /parkour\s*fail/i, category: "risky_stunts", severity: "high" },
    { regex: /rooftop\s*(run|jump|climb)/i, category: "risky_stunts", severity: "high" },
    { regex: /fire\s*challenge/i, category: "risky_stunts", severity: "high" },
    { regex: /knife\s*challenge/i, category: "risky_stunts", severity: "high" },
    { regex: /electric\s*shock/i, category: "risky_stunts", severity: "high" },
    { regex: /don'?t\s*try\s*this/i, category: "risky_stunts", severity: "high" },
    { regex: /almost\s*died/i, category: "risky_stunts", severity: "high" },
    { regex: /nearly\s*killed/i, category: "risky_stunts", severity: "high" },
    { regex: /choking\s*challenge/i, category: "risky_stunts", severity: "high" },
    { regex: /blackout\s*challenge/i, category: "risky_stunts", severity: "high" },
    { regex: /tide\s*pod/i, category: "risky_stunts", severity: "high" },
    { regex: /milk\s*crate/i, category: "risky_stunts", severity: "medium" },
  ],
  MATURE_REALITY_PATTERNS: [
    { regex: /true\s*crime/i, category: "mature_reality", severity: "high" },
    { regex: /murder\s*(mystery|story|case|documentary)/i, category: "mature_reality", severity: "high" },
    { regex: /serial\s*killer/i, category: "mature_reality", severity: "high" },
    { regex: /horror\s*story/i, category: "mature_reality", severity: "medium" },
    { regex: /scary\s*(story|experience|encounter)/i, category: "mature_reality", severity: "medium" },
    { regex: /creepy\s*pasta/i, category: "mature_reality", severity: "medium" },
    { regex: /disturbing\s*(facts|truth|reality)/i, category: "mature_reality", severity: "high" },
    { regex: /dark\s*web/i, category: "mature_reality", severity: "high" },
    { regex: /gore/i, category: "mature_reality", severity: "high" },
    { regex: /nsfw/i, category: "mature_reality", severity: "high" },
    { regex: /18\+/i, category: "mature_reality", severity: "high" },
    { regex: /mature\s*(audience|content|themes)/i, category: "mature_reality", severity: "high" },
    { regex: /drama\s*alert/i, category: "mature_reality", severity: "medium" },
    { regex: /callout\s*(post|video)/i, category: "mature_reality", severity: "medium" },
  ],
  PROTECTION_LEVELS: {
    none: { categories: [], severityThreshold: null },
    basic: { categories: ["brainrot", "social_engineering", "risky_stunts"], severityThreshold: "high" },
    moderate: { categories: ["brainrot", "social_engineering", "risky_stunts", "mature_reality"], severityThreshold: "medium" },
    maximum: { categories: ["brainrot", "social_engineering", "risky_stunts", "mature_reality"], severityThreshold: "low" },
  },
  SEVERITY_ORDER: { high: 3, medium: 2, low: 1 },
  CATEGORY_LABELS: {
    brainrot: "Brainrot",
    social_engineering: "Social Engineering",
    risky_stunts: "Risky Stunts",
    mature_reality: "Mature Content",
  }
};

INTERCEPTOR_CONFIG.ALL_PATTERNS = [].concat(
  INTERCEPTOR_CONFIG.BRAINROT_PATTERNS,
  INTERCEPTOR_CONFIG.SOCIAL_ENGINEERING_PATTERNS,
  INTERCEPTOR_CONFIG.RISKY_STUNT_PATTERNS,
  INTERCEPTOR_CONFIG.MATURE_REALITY_PATTERNS
);
